apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kzbn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0013-tenant/tkrw-pr712-0075-0013-app/devfile-sample-kzbn@sha256:3ec45e04c9579af800d430311f1524656d4c061eee126fb91b1b6ab3a9c48de8
        name: my-nodejs
        resources: {}
status: {}
